force-app/main/default/objects/Contact/fields/External_UUID__c.field-meta.xml
<CustomField>
    <fullName>External_UUID__c</fullName>
    <externalId>true</externalId>
    <label>External UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>N26_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/N26_Product__c.object-meta.xml
<CustomObject>
    <label>N26 Product</label>
    <nameField>
        <displayFormat>N26-{000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>N26 Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Monthly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cost__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>N26 Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>N26_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactRestResource.cls
@RestResource(urlMapping='/contactproduct/*')
global class ContactRestResource {

    @HttpGet
    global static void doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        //Get the uuid from the request URI
        String uuid = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        try {
            List<Contact> cList = [SELECT FirstName, LastName, Product__c, Home_Country__c FROM Contact WHERE External_UUID__c = :uuid];
            if(cList.isEmpty()) {
                res.statusCode = 404;
                res.responseBody = Blob.valueOf('{"error": "Contact not found"}');
                return;
            }
            Contact c = cList.get(0);
            List<N26_Product__c> productsList = [SELECT Id, Product__c, Monthly_Cost__c, ATM_Fee__c, Replacement_Cost__c, Currency__c FROM N26_Product__c WHERE Product__c = :c.Product__c AND Country__c = :c.Home_Country__c];
            if(productsList.isEmpty()) {
                res.statusCode = 404;
                res.responseBody = Blob.valueOf('{"error": "Product not found"}');
                return;
            }
            N26_Product__c cp = productsList.get(0);
            ContactProductDetails cpd = new ContactProductDetails(c.firstName, c.lastName, c.Home_Country__c, new ProductDetails(cp.Product__c, cp.Currency__c, cp.Monthly_Cost__c, cp.ATM_Fee__c, cp.Replacement_Cost__c));
            res.responseBody = Blob.valueOf(JSON.serializePretty(cpd));
            res.statusCode = 200;
        } catch(Exception e) {
            System.debug('GET Request error for URI ' + req.requestURI + ': ' + e.getMessage());
            res.statusCode = 500;
            res.responseBody = Blob.valueOf('{"error": "Internal server error"}');
        }
    }

    //Wrapper classes for contact and product details
    global class ContactProductDetails {
        public String firstName;
        public String lastName;
        public String countryCode;
        public ProductDetails product;
        public ContactProductDetails(String firstName, String lastName, String countryCode, ProductDetails product) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.countryCode = countryCode;
            this.product = product;
        }
    }

    global class ProductDetails {
        public String productName;
        public String currencyCode;
        public Decimal monthlyCost;
        public Decimal atmFeePercent;
        public Decimal replacementCost;
        public ProductDetails(String productName, String currencyCode, Decimal monthlyCost, Decimal atmFeePercent, Decimal replacementCost) {
            this.productName = productName;
            this.currencyCode = currencyCode;
            this.monthlyCost = monthlyCost;
            this.atmFeePercent = atmFeePercent;
            this.replacementCost = replacementCost;
        }
    }
}