force-app/main/default/objects/Contact/fields/External_UUID__c.field-meta.xml
<CustomField>
    <fullName>External_UUID__c</fullName>
    <externalId>true</externalId>
    <label>External UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>N26_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/N26_Product__c.object-meta.xml
<CustomObject>
    <label>N26 Product</label>
    <nameField>
        <displayFormat>N26-{000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>N26 Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Monthly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cost__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>N26 Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>N26_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactRestResourceTest.cls
@isTest
public class ContactRestResourceTest {
    private static String REQUEST_URI = 'services/apexrest/contactproduct';

    @TestSetup
    static void makeData() {
        List<SObject> recordsToInsert = new List<SObject>();
        Contact testContact = new Contact(FirstName = 'firstName', LastName = 'lastName', Home_Country__c = 'DE', Product__c = 'Standard', External_UUID__c = 'test-uuid');
        recordsToInsert.add(testContact);
        Contact testContactFail = new Contact(FirstName = 'firstNameFail', LastName = 'lastNameFail', Home_Country__c = 'FR', Product__c = 'Standard', External_UUID__c = 'test-uuid-fail');
        recordsToInsert.add(testContactFail);
        N26_Product__c testProduct = new N26_Product__c(Product__c = 'Standard', Country__c = 'DE', Currency__c = 'EUR', Monthly_Cost__c = 0, ATM_Fee__c = 1.7, Replacement_Cost__c = 6);
        recordsToInsert.add(testProduct);
        insert recordsToInsert;
    }

    @isTest
    static void doGetTest() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = REQUEST_URI + '/test-uuid';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        ContactRestResource.doGet();
        Test.stopTest();
        System.assertEquals(200, res.statusCode);
        System.assert(res.responseBody.toString().contains('Standard'));
    }

    @isTest
    static void doGetFailNoContactTest() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = REQUEST_URI + '/invalid-uuid';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        ContactRestResource.doGet();
        Test.stopTest();
        System.assertEquals(404, res.statusCode);
        System.assert(res.responseBody.toString().contains('Contact not found'));
    }

    @isTest
    static void doGetFailNoProductTest() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = REQUEST_URI + '/test-uuid-fail';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        ContactRestResource.doGet();
        Test.stopTest();
        System.assertEquals(404, res.statusCode);
        System.assert(res.responseBody.toString().contains('Product not found'));
    }
}