force-app/main/default/objects/Contact/fields/External_UUID__c.field-meta.xml
<CustomField>
    <fullName>External_UUID__c</fullName>
    <externalId>true</externalId>
    <label>External UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>N26_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/N26_Product__c.object-meta.xml
<CustomObject>
    <label>N26 Product</label>
    <nameField>
        <displayFormat>N26-{000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>N26 Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Monthly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cost__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>N26 Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>N26_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/N26ProductDetailControllerTest.cls
@isTest
public with sharing class N26ProductDetailControllerTest {
    @TestSetup
    static void makeData() {
        List<SObject> recordsToInsert = new List<SObject>();
        Contact testContact = new Contact(FirstName = 'firstName', LastName = 'lastName', Home_Country__c = 'DE', Product__c = 'Standard', External_UUID__c = 'test-uuid');
        recordsToInsert.add(testContact);
        N26_Product__c testProduct = new N26_Product__c(Product__c = 'Standard', Country__c = 'DE', Currency__c = 'EUR', Monthly_Cost__c = 0, ATM_Fee__c = 1.7, Replacement_Cost__c = 6);
        recordsToInsert.add(testProduct);
        insert recordsToInsert;  
    }

    @isTest
    static void getProductDetailsTest() {
        Id contactId = [SELECT Id FROM Contact WHERE External_UUID__c = 'test-uuid' LIMIT 1].Id;
        N26_Product__c p = N26ProductDetailController.getProductDetails(contactId);
        System.assertEquals('Standard', p.Product__c);
    }

    @isTest
    static void getProductDetailsNoContactTest() {
        try {
            N26_Product__c p =  N26ProductDetailController.getProductDetails('0030000000000000AA');
        } catch(AuraHandledException e) {
            System.assert(e != null);
        }
    }

    @isTest
    static void getProductDetailsNoProductTest() {
        Contact c = [SELECT Id, Product__c FROM Contact WHERE External_UUID__c = 'test-uuid' LIMIT 1];
        c.Product__c = 'Metal';
        update c;
        try {
            N26_Product__c p =  N26ProductDetailController.getProductDetails(c.Id);
        } catch(AuraHandledException e) {
            System.assert(e != null);
        }
    }
}