force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>N26_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/N26_Product__c.object-meta.xml
<CustomObject>
    <label>N26 Product</label>
    <nameField>
        <displayFormat>N26-{000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>N26 Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Monthly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cost__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>N26 Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>N26_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/N26_Product__c/fields/Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/N26ProductDetailController.cls
public class N26ProductDetailController {

    @AuraEnabled(cacheable=true)
    public static N26_Product__c getProductDetails(String contactId) {
        try {
            List<Contact> cList = [SELECT Product__c, Home_Country__c FROM Contact WHERE Id = :contactId];
            if(cList.isEmpty()) {
                throw new HandledException('No contact with Id ' + contactId + ' was found');
            }
            Contact c = cList.get(0);
            List<N26_Product__c> productsList = [SELECT Id, Product__c, Monthly_Cost__c, ATM_Fee__c, Replacement_Cost__c, Currency__c FROM N26_Product__c WHERE Product__c = :c.Product__c AND Country__c = :c.Home_Country__c];
            if(productsList.isEmpty()) {
                throw new HandledException('No ' + c.Product__c + ' product available for ' + c.Home_Country__c);
            }
            return productsList.get(0);
        } catch (HandledException e) {
            throw new AuraHandledException(e.getMessage());
        } catch (Exception e) {
            throw new AuraHandledException('An unexpected error occurred: ' + e.getMessage());
        }
    }
}